version: '3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 33066:3306
    environment:
      MYSQL_DATABASE: tortilla-fresca
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
  tortilla-fresca:
    image: node:8
    volumes:
      - ./:/usr/src/app/
    working_dir: /usr/src/app/
    command: ['yarn', 'develop']
    depends_on:
      - db
    links:
      - db
    ports: 
      - 1337:1337